[package]
name = "proto-build"
version = "0.1.0"
edition = "2021"
publish = false
rust-version = "1.57"
license = "Apache-2.0"

[dependencies]
prost = "0.11"
prost-build = "0.11"
regex = "1"
tonic = { git = "https://github.com/leejw51crypto/tonic.git", branch="cronos", default-features = false, features = ["codegen", "prost", "transport"] }
tonic-build = { version = "0.9", default-features = false, features = ["prost", "transport"] }
walkdir = "2"
